/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.CSDL_DAO;
import DAO.datPhong_DAO;
import DAO.datban_DAO;
import POJO.databan;
import POJO.datphong;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dinht
 */
public class DatBanDatPhong_GUI extends javax.swing.JFrame {

    /**
     * Creates new form DatBanDatPhong_GUI
     */
   
    CSDL_DAO kn=new CSDL_DAO();
    DefaultTableModel dtmDatBanFood= new DefaultTableModel();
    DefaultTableModel dtmRoom= new DefaultTableModel();
    DefaultTableModel dtmTableFood= new DefaultTableModel();
    DefaultTableModel dtmDatRoom= new DefaultTableModel();
    databan db=new databan();
    datban_DAO dbDao=new datban_DAO();
    datphong dp=new datphong();
    datPhong_DAO dpDAO=new datPhong_DAO();
    
    public DatBanDatPhong_GUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        String []tieudeDatBan={"Mã đặt bàn","Tên khách đặt","Số điện thoại","Tên bàn"};
        String []tieudeDatPhong={"Mã đặt phòng","Tên khách đặt","Số điện thoại","Tên phòng"};
        String []tieuDeBanAnFood={"Mã bàn","Tên bàn","Trạng thái"};
        String []tieuDeRoom={"Mã phòng","Tên phòng","Trạng thái"};
        
        dtmDatBanFood.setColumnIdentifiers(tieudeDatBan);
        dtmTableFood.setColumnIdentifiers(tieuDeBanAnFood);
        dtmRoom.setColumnIdentifiers(tieuDeRoom);
        dtmDatRoom.setColumnIdentifiers(tieudeDatPhong);
        
        tbPhongAn.setModel(dtmRoom);
       tbDatBan.setModel(dtmDatBanFood);
       
       tbDatPhong.setModel(dtmDatRoom);
       tbMainBanAn.setModel(dtmTableFood);
       kn.open();
       hienThiBanAn();
       LoadRoom();
       
       //LoadDatBan();
        htdsBanAnDat();
        htdsPhongAnDat();
       //LoadDatRoom();
       txtIDHuyBan.setEnabled(false);
       txtIDHuyPhong.setEnabled(false);
       txtIdBan.setEnabled(false);
       txtIdPhong.setEnabled(false);
       btnDatBan.setEnabled(false);
       btnDatPhong.setEnabled(false);
       btnHuyBan.setEnabled(false);
       btnHuyDatPhong.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDatBan = new javax.swing.JTable();
        btnHuyBan = new javax.swing.JButton();
        txtIDHuyBan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbDatPhong = new javax.swing.JTable();
        btnHuyDatPhong = new javax.swing.JButton();
        txtIDHuyPhong = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbMainBanAn = new javax.swing.JTable();
        txtIdBan = new javax.swing.JTextField();
        txtTenDatBan = new javax.swing.JTextField();
        btnDatBan = new javax.swing.JButton();
        txtSDTDatBan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbPhongAn = new javax.swing.JTable();
        txtIdPhong = new javax.swing.JTextField();
        txtTenPhong = new javax.swing.JTextField();
        txtSDTDatPhong = new javax.swing.JTextField();
        btnDatPhong = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnQuayLaiMain = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Danh sách bàn đã đặt", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 15))); // NOI18N
        jPanel1.setToolTipText("Danh sách đặt bàn");

        tbDatBan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tbDatBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbDatBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDatBanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbDatBan);

        btnHuyBan.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnHuyBan.setText("Hủy bàn");
        btnHuyBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyBanActionPerformed(evt);
            }
        });

        txtIDHuyBan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Mã đặt bàn");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnHuyBan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(txtIDHuyBan, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIDHuyBan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuyBan, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách phòng đã đặt", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 15))); // NOI18N

        tbDatPhong.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tbDatPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbDatPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDatPhongMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbDatPhong);

        btnHuyDatPhong.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnHuyDatPhong.setText("Hủy đặt phòng");
        btnHuyDatPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyDatPhongActionPerformed(evt);
            }
        });

        txtIDHuyPhong.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Mã đặt phòng");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnHuyDatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(txtIDHuyPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtIDHuyPhong)
                        .addComponent(btnHuyDatPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                    .addComponent(jLabel8))
                .addGap(7, 7, 7))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách bàn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 15))); // NOI18N

        tbMainBanAn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tbMainBanAn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbMainBanAn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMainBanAnMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbMainBanAn);

        txtIdBan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        txtTenDatBan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        btnDatBan.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnDatBan.setText("Đặt bàn");
        btnDatBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatBanActionPerformed(evt);
            }
        });

        txtSDTDatBan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Mã bàn");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Họ tên khách");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Số điện thoại");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtSDTDatBan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(btnDatBan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdBan)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenDatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenDatBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSDTDatBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách phòng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 15))); // NOI18N

        tbPhongAn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tbPhongAn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbPhongAn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPhongAnMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbPhongAn);

        txtIdPhong.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        txtTenPhong.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        txtSDTDatPhong.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        btnDatPhong.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnDatPhong.setText("Đặt phòng");
        btnDatPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatPhongActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Mã phòng");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Họ tên khách");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Số điện thoại");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(txtIdPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSDTDatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDatPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))))
                .addGap(17, 17, 17))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTenPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSDTDatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );

        btnQuayLaiMain.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnQuayLaiMain.setText("< Quay lại");
        btnQuayLaiMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiMainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnQuayLaiMain, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(btnQuayLaiMain, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbMainBanAnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMainBanAnMouseClicked
        int row=tbMainBanAn.getSelectedRow();
        txtIdBan.setText((String)tbMainBanAn.getValueAt(row, 0));
          txtTenDatBan.requestFocus();
        if(row>=0)
        {
               
                btnDatBan.setEnabled(true);
            
        }
        

        //hienThiMainBill((String)tbMainBanAn.getValueAt(row, 0));

    }//GEN-LAST:event_tbMainBanAnMouseClicked

    private void tbPhongAnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPhongAnMouseClicked
        // TODO add your handling code here:
         int row=tbPhongAn.getSelectedRow();
        txtIdPhong.setText((String)tbPhongAn.getValueAt(row, 0));
        txtTenPhong.requestFocus();
         if(row>=0)
        {
               
                btnDatPhong.setEnabled(true);
            
        }
    }//GEN-LAST:event_tbPhongAnMouseClicked

    private void btnDatBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatBanActionPerformed
        
        db.setTen(txtTenDatBan.getText());
        db.setSdt(txtSDTDatBan.getText());
        db.setIdBan(Integer.parseInt(txtIdBan.getText()));
        dbDao.themBanDat(db);
        JOptionPane.showMessageDialog(this, "Thêm thành công");
        htdsBanAnDat();
            
    }//GEN-LAST:event_btnDatBanActionPerformed

    private void btnDatPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatPhongActionPerformed
        // TODO add your handling code here:
        String sqlUpdata ="insert into datPhong values(N'"+txtTenPhong.getText()+"','"+txtSDTDatPhong.getText()+"',"+txtIdPhong.getText()+") ";
            int x ;
            
        try {
            x= kn.statement.executeUpdate(sqlUpdata);
             if(x>0)
            {
                JOptionPane.showMessageDialog(this, "Đặt phòng thành công");
               
                LoadRoom();
                htdsPhongAnDat();
            }
             else
             {
                 JOptionPane.showMessageDialog(this, "Đặt phòng thất bại");
             }
        } catch (SQLException ex) {
            Logger.getLogger(DatBanDatPhong_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDatPhongActionPerformed

    private void tbDatBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDatBanMouseClicked
        // TODO add your handling code here:
         int row=tbDatBan.getSelectedRow();
        txtIDHuyBan.setText(String.valueOf(tbDatBan.getValueAt(row, 0)));
         if(row>=0)
        {
               
                btnHuyBan.setEnabled(true);
            
        }
    }//GEN-LAST:event_tbDatBanMouseClicked

    private void tbDatPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDatPhongMouseClicked
        // TODO add your handling code here:
        int row=tbDatPhong.getSelectedRow();
        txtIDHuyPhong.setText(String.valueOf(tbDatPhong.getValueAt(row, 0)));
         if(row>=0)
        {
               
                btnHuyDatPhong.setEnabled(true);
            
        }
    }//GEN-LAST:event_tbDatPhongMouseClicked

    private void btnHuyBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyBanActionPerformed
        // TODO add your handling code here:
        int row=tbDatBan.getSelectedRow();
        if(row==-1)
        {
            JOptionPane.showMessageDialog(this, "Chọn bàn cần hủy");
        }
        else
                {
                    int x=JOptionPane.showConfirmDialog(this, "Thông báo","Bạn có muốn hủy đặt bàn đó không",JOptionPane.YES_NO_CANCEL_OPTION);
                    if(x==JOptionPane.YES_OPTION)
                    {
                         db.setId(Integer.parseInt(txtIDHuyBan.getText()));
                            dbDao.xBanDat(db);
                             String sql1="  update banAn set trang_Thai=N'Trống' where id="+tbDatBan.getValueAt(row, 3).toString()+"";
                            int n1=kn.excuteUpdate(sql1);
                            JOptionPane.showMessageDialog(this, "Hủy thành công");
                        htdsBanAnDat(); 
                        hienThiBanAn();
                    }
                    
                }
        
    }//GEN-LAST:event_btnHuyBanActionPerformed

    private void btnHuyDatPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyDatPhongActionPerformed
        // TODO add your handling code here:
         int row=tbDatPhong.getSelectedRow();
        if(row==-1)
        {
            JOptionPane.showMessageDialog(this, "Chọn phòng cần hủy");
        }
        else
                {
                    int x=JOptionPane.showConfirmDialog(this, "Thông báo","Bạn có muốn hủy đặt phòng đó không",JOptionPane.YES_NO_CANCEL_OPTION);
                    if(x==JOptionPane.YES_OPTION)
                    {
                         dp.setId(Integer.parseInt(txtIDHuyPhong.getText()));
                         
                         
                          String sql1="update PhongAn set trangThai=N'Trống' where id="+tbDatPhong.getValueAt(row, 3).toString()+"";
                            int n1=kn.excuteUpdate(sql1);
                            
                         
                            dpDAO.xPhongDat(dp);
                            JOptionPane.showMessageDialog(this, "Hủy thành công");
                        htdsPhongAnDat(); 
                        LoadRoom();
                    }
                    
                }
    }//GEN-LAST:event_btnHuyDatPhongActionPerformed

    private void btnQuayLaiMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiMainActionPerformed
        // TODO add your handling code here:
        Main_GUI m=new Main_GUI();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnQuayLaiMainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatBanDatPhong_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatBanDatPhong_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatBanDatPhong_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatBanDatPhong_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatBanDatPhong_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDatBan;
    private javax.swing.JButton btnDatPhong;
    private javax.swing.JButton btnHuyBan;
    private javax.swing.JButton btnHuyDatPhong;
    private javax.swing.JButton btnQuayLaiMain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tbDatBan;
    private javax.swing.JTable tbDatPhong;
    private javax.swing.JTable tbMainBanAn;
    private javax.swing.JTable tbPhongAn;
    private javax.swing.JTextField txtIDHuyBan;
    private javax.swing.JTextField txtIDHuyPhong;
    private javax.swing.JTextField txtIdBan;
    private javax.swing.JTextField txtIdPhong;
    private javax.swing.JTextField txtSDTDatBan;
    private javax.swing.JTextField txtSDTDatPhong;
    private javax.swing.JTextField txtTenDatBan;
    private javax.swing.JTextField txtTenPhong;
    // End of variables declaration//GEN-END:variables

 private void hienThiBanAn() {
       dtmTableFood.setRowCount(0);
        try{
            kn.statement= kn.connection.createStatement();
                
        }catch (SQLException ex)
        {
            ex.printStackTrace();
        }
        String sqlSelect="select *from banAn";
        try{
            kn.resultSet=kn.statement.executeQuery(sqlSelect);
            while(kn.resultSet.next())
            {
                String ma= kn.resultSet.getString("id");
                String ten=kn.resultSet.getString("ten_Ban");
                String nam = kn.resultSet.getString("trang_Thai");
                Vector <Object> v = new Vector<Object>();
                v.add(ma);
                v.add(ten);
                v.add(nam);
                dtmTableFood.addRow(v);
                   
            }
        }catch(SQLException ex)
        {
            ex.printStackTrace();
        }
    }
 private void LoadRoom() {
        dtmRoom.setRowCount(0);
        try{
            kn.statement= kn.connection.createStatement();
                
        }catch (SQLException ex)
        {
            ex.printStackTrace();
        }
        String sqlSelect="select *from PhongAn";
        try{
            kn.resultSet=kn.statement.executeQuery(sqlSelect);
            while(kn.resultSet.next())
            {
                String ma= kn.resultSet.getString("id");
                String ten=kn.resultSet.getString("tenPhong");
                String nam = kn.resultSet.getString("trangThai");
                Vector <Object> v = new Vector<Object>();
                v.add(ma);
                v.add(ten);
                v.add(nam);
                dtmRoom.addRow(v);
                   
            }
        }catch(SQLException ex)
        {
            ex.printStackTrace();
        }}

    
    private void htdsBanAnDat()
   {
       ArrayList<POJO.databan> dsBA=datban_DAO.layDSDB();
      dtmDatBanFood.setRowCount(0);
       for(POJO.databan ba:dsBA)
       {
           Vector<Object> v=new Vector<Object>();
           v.add(ba.getId());
           v.add(ba.getTen());
          v.add(ba.getSdt());
          v.add(ba.getIdBan());
           dtmDatBanFood.addRow(v);
       }
       tbDatBan.setModel(dtmDatBanFood);
       
   }
    private void htdsPhongAnDat()
   {
       ArrayList<POJO.datphong> dsPA=datPhong_DAO.layDSDP();
      dtmDatRoom.setRowCount(0);
       for(POJO.datphong pa:dsPA)
       {
           Vector<Object> v=new Vector<Object>();
           v.add(pa.getId());
           v.add(pa.getTenKH());
          v.add(pa.getSdt());
          v.add(pa.getIdPhong());
           dtmDatRoom.addRow(v);
       }
       tbDatPhong.setModel(dtmDatRoom);
       
   }
}
