/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import DAO.CSDL_DAO;
import DAO.QL_Nhap_Kho_DAO;
import POJO.QL_Nhap_Kho_POJO;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
/**
 *
 * @author Admin
 */
public class QL_Nhap_Kho_GUI extends javax.swing.JFrame {

    /**
     * Creates new form QL_Nhap_Kho_GUI
     */
    DefaultTableModel dtm = new DefaultTableModel();
    Vector<String> tieuDe = new Vector<String>();
    Vector duLieu = new Vector();
    boolean them = false;
    boolean thayDoi = false;
    private float gia = 1000;
    //kết nối
    CSDL_DAO kn = new CSDL_DAO();
   
    public QL_Nhap_Kho_GUI() {
        initComponents();
        txt_maNguyenLieu.setEnabled(false);
        txt_donGia.setEnabled(false);
        this.setLocationRelativeTo(null);
        tieuDe.add("Mã Nguyên Liệu");
        
        tieuDe.add("Tên Nguyên Liệu");
        tieuDe.add("Ngày Nhập");
        tieuDe.add("Số Lượng");
        tieuDe.add("Đơn Giá");
        dtm.setColumnIdentifiers(tieuDe);
        tb_thongTinNguyenLieu.setModel(dtm);
        kn.open();
        setNgay();
        HienThiThucAn();
        txt_tenNguyenLieu.requestFocus();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_thongTinNguyenLieu = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_maNguyenLieu = new javax.swing.JTextField();
        txt_tenNguyenLieu = new javax.swing.JTextField();
        txt_soLuong = new javax.swing.JTextField();
        txt_donGia = new javax.swing.JTextField();
        btn_them = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_refesh = new javax.swing.JButton();
        btn_thoat = new javax.swing.JButton();
        txt_ngaynhap = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnQuayLai = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nhập Sản Phẩm Vào Kho", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(51, 51, 255))); // NOI18N

        tb_thongTinNguyenLieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_thongTinNguyenLieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_thongTinNguyenLieuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_thongTinNguyenLieu);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin nguyên liệu", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 15), new java.awt.Color(102, 102, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setText("Mã nguyên liệu");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setText("Tên nguyên liệu");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setText("Số lượng");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setText("Đơn giá");

        txt_maNguyenLieu.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txt_tenNguyenLieu.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txt_soLuong.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txt_donGia.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        btn_them.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_xoa.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_sua.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_refesh.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btn_refesh.setText("Refesh");
        btn_refesh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refeshActionPerformed(evt);
            }
        });

        btn_thoat.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btn_thoat.setText("Thoát");
        btn_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoatActionPerformed(evt);
            }
        });

        txt_ngaynhap.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setText("Ngày nhập");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_refesh, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(btn_thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGap(56, 56, 56)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_maNguyenLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_tenNguyenLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_ngaynhap, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(108, 108, 108)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_soLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_donGia, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_maNguyenLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_tenNguyenLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ngaynhap, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_soLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_donGia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_refesh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btnQuayLai.setText("Quay lại");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(btnQuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_thongTinNguyenLieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_thongTinNguyenLieuMouseClicked
       int row = tb_thongTinNguyenLieu.getSelectedRow();
    txt_maNguyenLieu.setText(String.valueOf(tb_thongTinNguyenLieu.getValueAt(row, 0)));
    txt_tenNguyenLieu.setText((String)tb_thongTinNguyenLieu.getValueAt(row, 1));
    txt_ngaynhap.setText((String)tb_thongTinNguyenLieu.getValueAt(row, 2));
    txt_soLuong.setText(String.valueOf(tb_thongTinNguyenLieu.getValueAt(row, 3)));
    txt_donGia.setText(String.valueOf(tb_thongTinNguyenLieu.getValueAt(row, 4)));

    }//GEN-LAST:event_tb_thongTinNguyenLieuMouseClicked
 private void setNgay(){
        // Lấy thời gian hiện tại
            Date now = new Date();
      SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
      String dateString = format.format(now);
      txt_ngaynhap.setText(dateString);
    }
    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
    String tenmon = txt_tenNguyenLieu.getText();
    String ngay = txt_ngaynhap.getText();
    int soluong = 0;
    if (!txt_soLuong.getText().isEmpty()) {
        soluong = Integer.parseInt(txt_soLuong.getText());
    } else {
        JOptionPane.showMessageDialog(this, "Số lượng không được để trống!");
        return;
    }
    float dongia = 1000 * soluong;
    QL_Nhap_Kho_POJO ba = new QL_Nhap_Kho_POJO();
    ba.setTenNguyenLieu(tenmon);
    ba.setNgayNhap(ngay);
    ba.setSoluong(soluong);
    ba.setDongia(dongia);

    boolean kq = QL_Nhap_Kho_DAO.them_NL_VaoKho(ba);

    if (kq) {
        JOptionPane.showMessageDialog(this, "Thêm nguyên liệu vào kho thành công!");
    } else {
        JOptionPane.showMessageDialog(this, "Thêm nguyên liệu vào kho thất bại!");
    }

    HienThiThucAn();
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        String mamon = txt_maNguyenLieu.getText();
        int row = tb_thongTinNguyenLieu.getSelectedRow();
        if(row == -1 )
        {
            JOptionPane.showMessageDialog(this, "Chọn dòng cần xóa!!!");
            return;
        }
        else {
             int n = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa dòng này không ??","THÔNG BÁO",JOptionPane.YES_NO_OPTION);
             if(n == JOptionPane.NO_OPTION){
                 return;
             }else{
//                int ma = Integer.parseInt(txt_ma.getText());
                int ma = Integer.parseInt(tb_thongTinNguyenLieu.getValueAt(row, 0).toString());
                QL_Nhap_Kho_DAO.xoa_NL_Kho(ma);
                JOptionPane.showMessageDialog(this, "Xóa Thành Công");
                HienThiThucAn();
                }
        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
       int row = tb_thongTinNguyenLieu.getSelectedRow();
    if(row == -1) {
        JOptionPane.showMessageDialog(this, "Chọn dòng cần sửa!!!");
        return;
    }
    int id = Integer.parseInt(txt_maNguyenLieu.getText());
    String tenNguyenLieu = txt_tenNguyenLieu.getText();
    String ngayNhap = txt_ngaynhap.getText();
    int soLuong = Integer.parseInt(txt_soLuong.getText());
    float donGia = soLuong * gia;
    QL_Nhap_Kho_POJO ba = new QL_Nhap_Kho_POJO();
    ba.setId(id);
    ba.setTenNguyenLieu(tenNguyenLieu);
    ba.setNgayNhap(ngayNhap);
    ba.setSoluong(soLuong);
    ba.setDongia(donGia);
    boolean kq = QL_Nhap_Kho_DAO.sua_NL_Kho(ba);
    if(kq) {
        JOptionPane.showMessageDialog(this, "Sửa nguyên liệu thành công!");
    } else {
        JOptionPane.showMessageDialog(this, "Sửa nguyên liệu thất bại!");
    }
    HienThiThucAn();
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_refeshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refeshActionPerformed
        refesh();
        txt_tenNguyenLieu.requestFocus();
    }//GEN-LAST:event_btn_refeshActionPerformed

    private void btn_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoatActionPerformed
        int n = JOptionPane.showConfirmDialog(this, "Bạn Muốn Thoát", "Thông báo!!!", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if(n == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btn_thoatActionPerformed

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        // TODO add your handling code here:
        Admin_GUI m=new  Admin_GUI();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnQuayLaiActionPerformed
    private void refesh() {
        this.txt_maNguyenLieu.setText("");
        setNgay();
        this.txt_tenNguyenLieu.setText("");
        this.txt_soLuong.setText("");
        this.txt_donGia.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QL_Nhap_Kho_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QL_Nhap_Kho_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QL_Nhap_Kho_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QL_Nhap_Kho_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QL_Nhap_Kho_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btn_refesh;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_thoat;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_thongTinNguyenLieu;
    private javax.swing.JTextField txt_donGia;
    private javax.swing.JTextField txt_maNguyenLieu;
    private javax.swing.JTextField txt_ngaynhap;
    private javax.swing.JTextField txt_soLuong;
    private javax.swing.JTextField txt_tenNguyenLieu;
    // End of variables declaration//GEN-END:variables

   
    private void HienThiThucAn() {
        dtm.setRowCount(0);
        ArrayList<QL_Nhap_Kho_POJO> dsPB = QL_Nhap_Kho_DAO.layArrayList();
        dtm.setRowCount(0);
        for(QL_Nhap_Kho_POJO pb:dsPB)
        {
            Vector<Object> v = new Vector<Object>();
            v.add(pb.getId());
            v.add(pb.getTenNguyenLieu());
            v.add(pb.getNgayNhap());
            v.add(pb.getSoluong());
            v.add(pb.getDongia());
            dtm.addRow(v);
        }
        tb_thongTinNguyenLieu.setModel(dtm);
    }
}
